/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TutorialsRouteImport } from './routes/tutorials'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RoadmapsRouteImport } from './routes/roadmaps'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InternshipsRouteImport } from './routes/internships'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TutorialsSlugRouteImport } from './routes/tutorials.$slug'
import { Route as LearnSlugRouteImport } from './routes/learn.$slug'
import { Route as ApiContactRouteImport } from './routes/api/contact'
import { Route as ApiNewsletterSubscribeRouteImport } from './routes/api/newsletter/subscribe'
import { Route as ApiInternshipsApplyRouteImport } from './routes/api/internships/apply'

const TutorialsRoute = TutorialsRouteImport.update({
  id: '/tutorials',
  path: '/tutorials',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RoadmapsRoute = RoadmapsRouteImport.update({
  id: '/roadmaps',
  path: '/roadmaps',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InternshipsRoute = InternshipsRouteImport.update({
  id: '/internships',
  path: '/internships',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TutorialsSlugRoute = TutorialsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => TutorialsRoute,
} as any)
const LearnSlugRoute = LearnSlugRouteImport.update({
  id: '/learn/$slug',
  path: '/learn/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiContactRoute = ApiContactRouteImport.update({
  id: '/api/contact',
  path: '/api/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNewsletterSubscribeRoute = ApiNewsletterSubscribeRouteImport.update({
  id: '/api/newsletter/subscribe',
  path: '/api/newsletter/subscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInternshipsApplyRoute = ApiInternshipsApplyRouteImport.update({
  id: '/api/internships/apply',
  path: '/api/internships/apply',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/contact': typeof ContactRoute
  '/internships': typeof InternshipsRoute
  '/login': typeof LoginRoute
  '/roadmaps': typeof RoadmapsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tutorials': typeof TutorialsRouteWithChildren
  '/api/contact': typeof ApiContactRoute
  '/learn/$slug': typeof LearnSlugRoute
  '/tutorials/$slug': typeof TutorialsSlugRoute
  '/api/internships/apply': typeof ApiInternshipsApplyRoute
  '/api/newsletter/subscribe': typeof ApiNewsletterSubscribeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/contact': typeof ContactRoute
  '/internships': typeof InternshipsRoute
  '/login': typeof LoginRoute
  '/roadmaps': typeof RoadmapsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tutorials': typeof TutorialsRouteWithChildren
  '/api/contact': typeof ApiContactRoute
  '/learn/$slug': typeof LearnSlugRoute
  '/tutorials/$slug': typeof TutorialsSlugRoute
  '/api/internships/apply': typeof ApiInternshipsApplyRoute
  '/api/newsletter/subscribe': typeof ApiNewsletterSubscribeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/contact': typeof ContactRoute
  '/internships': typeof InternshipsRoute
  '/login': typeof LoginRoute
  '/roadmaps': typeof RoadmapsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tutorials': typeof TutorialsRouteWithChildren
  '/api/contact': typeof ApiContactRoute
  '/learn/$slug': typeof LearnSlugRoute
  '/tutorials/$slug': typeof TutorialsSlugRoute
  '/api/internships/apply': typeof ApiInternshipsApplyRoute
  '/api/newsletter/subscribe': typeof ApiNewsletterSubscribeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/contact'
    | '/internships'
    | '/login'
    | '/roadmaps'
    | '/sitemap.xml'
    | '/tutorials'
    | '/api/contact'
    | '/learn/$slug'
    | '/tutorials/$slug'
    | '/api/internships/apply'
    | '/api/newsletter/subscribe'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/contact'
    | '/internships'
    | '/login'
    | '/roadmaps'
    | '/sitemap.xml'
    | '/tutorials'
    | '/api/contact'
    | '/learn/$slug'
    | '/tutorials/$slug'
    | '/api/internships/apply'
    | '/api/newsletter/subscribe'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/contact'
    | '/internships'
    | '/login'
    | '/roadmaps'
    | '/sitemap.xml'
    | '/tutorials'
    | '/api/contact'
    | '/learn/$slug'
    | '/tutorials/$slug'
    | '/api/internships/apply'
    | '/api/newsletter/subscribe'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ContactRoute: typeof ContactRoute
  InternshipsRoute: typeof InternshipsRoute
  LoginRoute: typeof LoginRoute
  RoadmapsRoute: typeof RoadmapsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TutorialsRoute: typeof TutorialsRouteWithChildren
  ApiContactRoute: typeof ApiContactRoute
  LearnSlugRoute: typeof LearnSlugRoute
  ApiInternshipsApplyRoute: typeof ApiInternshipsApplyRoute
  ApiNewsletterSubscribeRoute: typeof ApiNewsletterSubscribeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tutorials': {
      id: '/tutorials'
      path: '/tutorials'
      fullPath: '/tutorials'
      preLoaderRoute: typeof TutorialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roadmaps': {
      id: '/roadmaps'
      path: '/roadmaps'
      fullPath: '/roadmaps'
      preLoaderRoute: typeof RoadmapsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/internships': {
      id: '/internships'
      path: '/internships'
      fullPath: '/internships'
      preLoaderRoute: typeof InternshipsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tutorials/$slug': {
      id: '/tutorials/$slug'
      path: '/$slug'
      fullPath: '/tutorials/$slug'
      preLoaderRoute: typeof TutorialsSlugRouteImport
      parentRoute: typeof TutorialsRoute
    }
    '/learn/$slug': {
      id: '/learn/$slug'
      path: '/learn/$slug'
      fullPath: '/learn/$slug'
      preLoaderRoute: typeof LearnSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/contact': {
      id: '/api/contact'
      path: '/api/contact'
      fullPath: '/api/contact'
      preLoaderRoute: typeof ApiContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/newsletter/subscribe': {
      id: '/api/newsletter/subscribe'
      path: '/api/newsletter/subscribe'
      fullPath: '/api/newsletter/subscribe'
      preLoaderRoute: typeof ApiNewsletterSubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/internships/apply': {
      id: '/api/internships/apply'
      path: '/api/internships/apply'
      fullPath: '/api/internships/apply'
      preLoaderRoute: typeof ApiInternshipsApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface TutorialsRouteChildren {
  TutorialsSlugRoute: typeof TutorialsSlugRoute
}

const TutorialsRouteChildren: TutorialsRouteChildren = {
  TutorialsSlugRoute: TutorialsSlugRoute,
}

const TutorialsRouteWithChildren = TutorialsRoute._addFileChildren(
  TutorialsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ContactRoute: ContactRoute,
  InternshipsRoute: InternshipsRoute,
  LoginRoute: LoginRoute,
  RoadmapsRoute: RoadmapsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TutorialsRoute: TutorialsRouteWithChildren,
  ApiContactRoute: ApiContactRoute,
  LearnSlugRoute: LearnSlugRoute,
  ApiInternshipsApplyRoute: ApiInternshipsApplyRoute,
  ApiNewsletterSubscribeRoute: ApiNewsletterSubscribeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
