/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyRouteImport } from './routes/verify'
import { Route as TutorialsRouteImport } from './routes/tutorials'
import { Route as TermsOfServiceRouteImport } from './routes/terms-of-service'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RoadmapsRouteImport } from './routes/roadmaps'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InternshipsRouteImport } from './routes/internships'
import { Route as InternPortalRouteImport } from './routes/intern-portal'
import { Route as Google3fa6f359a7138e5fDothtmlRouteImport } from './routes/google3fa6f359a7138e5f[.]html'
import { Route as EventsRouteImport } from './routes/events'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VerifyTokenRouteImport } from './routes/verify_.$token'
import { Route as TutorialsSlugRouteImport } from './routes/tutorials_.$slug'
import { Route as RoadmapsSlugRouteImport } from './routes/roadmaps_.$slug'
import { Route as LearnSlugRouteImport } from './routes/learn.$slug'
import { Route as ApiContactRouteImport } from './routes/api/contact'
import { Route as ApiNewsletterSubscribeRouteImport } from './routes/api/newsletter/subscribe'
import { Route as ApiInternshipsApplyRouteImport } from './routes/api/internships/apply'

const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const TutorialsRoute = TutorialsRouteImport.update({
  id: '/tutorials',
  path: '/tutorials',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsOfServiceRoute = TermsOfServiceRouteImport.update({
  id: '/terms-of-service',
  path: '/terms-of-service',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RoadmapsRoute = RoadmapsRouteImport.update({
  id: '/roadmaps',
  path: '/roadmaps',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InternshipsRoute = InternshipsRouteImport.update({
  id: '/internships',
  path: '/internships',
  getParentRoute: () => rootRouteImport,
} as any)
const InternPortalRoute = InternPortalRouteImport.update({
  id: '/intern-portal',
  path: '/intern-portal',
  getParentRoute: () => rootRouteImport,
} as any)
const Google3fa6f359a7138e5fDothtmlRoute =
  Google3fa6f359a7138e5fDothtmlRouteImport.update({
    id: '/google3fa6f359a7138e5f.html',
    path: '/google3fa6f359a7138e5f.html',
    getParentRoute: () => rootRouteImport,
  } as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyTokenRoute = VerifyTokenRouteImport.update({
  id: '/verify_/$token',
  path: '/verify/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const TutorialsSlugRoute = TutorialsSlugRouteImport.update({
  id: '/tutorials_/$slug',
  path: '/tutorials/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const RoadmapsSlugRoute = RoadmapsSlugRouteImport.update({
  id: '/roadmaps_/$slug',
  path: '/roadmaps/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnSlugRoute = LearnSlugRouteImport.update({
  id: '/learn/$slug',
  path: '/learn/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiContactRoute = ApiContactRouteImport.update({
  id: '/api/contact',
  path: '/api/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNewsletterSubscribeRoute = ApiNewsletterSubscribeRouteImport.update({
  id: '/api/newsletter/subscribe',
  path: '/api/newsletter/subscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInternshipsApplyRoute = ApiInternshipsApplyRouteImport.update({
  id: '/api/internships/apply',
  path: '/api/internships/apply',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsRoute
  '/google3fa6f359a7138e5f.html': typeof Google3fa6f359a7138e5fDothtmlRoute
  '/intern-portal': typeof InternPortalRoute
  '/internships': typeof InternshipsRoute
  '/login': typeof LoginRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/roadmaps': typeof RoadmapsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/tutorials': typeof TutorialsRoute
  '/verify': typeof VerifyRoute
  '/api/contact': typeof ApiContactRoute
  '/learn/$slug': typeof LearnSlugRoute
  '/roadmaps/$slug': typeof RoadmapsSlugRoute
  '/tutorials/$slug': typeof TutorialsSlugRoute
  '/verify/$token': typeof VerifyTokenRoute
  '/api/internships/apply': typeof ApiInternshipsApplyRoute
  '/api/newsletter/subscribe': typeof ApiNewsletterSubscribeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsRoute
  '/google3fa6f359a7138e5f.html': typeof Google3fa6f359a7138e5fDothtmlRoute
  '/intern-portal': typeof InternPortalRoute
  '/internships': typeof InternshipsRoute
  '/login': typeof LoginRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/roadmaps': typeof RoadmapsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/tutorials': typeof TutorialsRoute
  '/verify': typeof VerifyRoute
  '/api/contact': typeof ApiContactRoute
  '/learn/$slug': typeof LearnSlugRoute
  '/roadmaps/$slug': typeof RoadmapsSlugRoute
  '/tutorials/$slug': typeof TutorialsSlugRoute
  '/verify/$token': typeof VerifyTokenRoute
  '/api/internships/apply': typeof ApiInternshipsApplyRoute
  '/api/newsletter/subscribe': typeof ApiNewsletterSubscribeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsRoute
  '/google3fa6f359a7138e5f.html': typeof Google3fa6f359a7138e5fDothtmlRoute
  '/intern-portal': typeof InternPortalRoute
  '/internships': typeof InternshipsRoute
  '/login': typeof LoginRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/roadmaps': typeof RoadmapsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/tutorials': typeof TutorialsRoute
  '/verify': typeof VerifyRoute
  '/api/contact': typeof ApiContactRoute
  '/learn/$slug': typeof LearnSlugRoute
  '/roadmaps_/$slug': typeof RoadmapsSlugRoute
  '/tutorials_/$slug': typeof TutorialsSlugRoute
  '/verify_/$token': typeof VerifyTokenRoute
  '/api/internships/apply': typeof ApiInternshipsApplyRoute
  '/api/newsletter/subscribe': typeof ApiNewsletterSubscribeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/contact'
    | '/events'
    | '/google3fa6f359a7138e5f.html'
    | '/intern-portal'
    | '/internships'
    | '/login'
    | '/privacy-policy'
    | '/roadmaps'
    | '/sitemap.xml'
    | '/terms-of-service'
    | '/tutorials'
    | '/verify'
    | '/api/contact'
    | '/learn/$slug'
    | '/roadmaps/$slug'
    | '/tutorials/$slug'
    | '/verify/$token'
    | '/api/internships/apply'
    | '/api/newsletter/subscribe'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/contact'
    | '/events'
    | '/google3fa6f359a7138e5f.html'
    | '/intern-portal'
    | '/internships'
    | '/login'
    | '/privacy-policy'
    | '/roadmaps'
    | '/sitemap.xml'
    | '/terms-of-service'
    | '/tutorials'
    | '/verify'
    | '/api/contact'
    | '/learn/$slug'
    | '/roadmaps/$slug'
    | '/tutorials/$slug'
    | '/verify/$token'
    | '/api/internships/apply'
    | '/api/newsletter/subscribe'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/contact'
    | '/events'
    | '/google3fa6f359a7138e5f.html'
    | '/intern-portal'
    | '/internships'
    | '/login'
    | '/privacy-policy'
    | '/roadmaps'
    | '/sitemap.xml'
    | '/terms-of-service'
    | '/tutorials'
    | '/verify'
    | '/api/contact'
    | '/learn/$slug'
    | '/roadmaps_/$slug'
    | '/tutorials_/$slug'
    | '/verify_/$token'
    | '/api/internships/apply'
    | '/api/newsletter/subscribe'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ContactRoute: typeof ContactRoute
  EventsRoute: typeof EventsRoute
  Google3fa6f359a7138e5fDothtmlRoute: typeof Google3fa6f359a7138e5fDothtmlRoute
  InternPortalRoute: typeof InternPortalRoute
  InternshipsRoute: typeof InternshipsRoute
  LoginRoute: typeof LoginRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  RoadmapsRoute: typeof RoadmapsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsOfServiceRoute: typeof TermsOfServiceRoute
  TutorialsRoute: typeof TutorialsRoute
  VerifyRoute: typeof VerifyRoute
  ApiContactRoute: typeof ApiContactRoute
  LearnSlugRoute: typeof LearnSlugRoute
  RoadmapsSlugRoute: typeof RoadmapsSlugRoute
  TutorialsSlugRoute: typeof TutorialsSlugRoute
  VerifyTokenRoute: typeof VerifyTokenRoute
  ApiInternshipsApplyRoute: typeof ApiInternshipsApplyRoute
  ApiNewsletterSubscribeRoute: typeof ApiNewsletterSubscribeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tutorials': {
      id: '/tutorials'
      path: '/tutorials'
      fullPath: '/tutorials'
      preLoaderRoute: typeof TutorialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms-of-service': {
      id: '/terms-of-service'
      path: '/terms-of-service'
      fullPath: '/terms-of-service'
      preLoaderRoute: typeof TermsOfServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roadmaps': {
      id: '/roadmaps'
      path: '/roadmaps'
      fullPath: '/roadmaps'
      preLoaderRoute: typeof RoadmapsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/internships': {
      id: '/internships'
      path: '/internships'
      fullPath: '/internships'
      preLoaderRoute: typeof InternshipsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intern-portal': {
      id: '/intern-portal'
      path: '/intern-portal'
      fullPath: '/intern-portal'
      preLoaderRoute: typeof InternPortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/google3fa6f359a7138e5f.html': {
      id: '/google3fa6f359a7138e5f.html'
      path: '/google3fa6f359a7138e5f.html'
      fullPath: '/google3fa6f359a7138e5f.html'
      preLoaderRoute: typeof Google3fa6f359a7138e5fDothtmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify_/$token': {
      id: '/verify_/$token'
      path: '/verify/$token'
      fullPath: '/verify/$token'
      preLoaderRoute: typeof VerifyTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tutorials_/$slug': {
      id: '/tutorials_/$slug'
      path: '/tutorials/$slug'
      fullPath: '/tutorials/$slug'
      preLoaderRoute: typeof TutorialsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roadmaps_/$slug': {
      id: '/roadmaps_/$slug'
      path: '/roadmaps/$slug'
      fullPath: '/roadmaps/$slug'
      preLoaderRoute: typeof RoadmapsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/$slug': {
      id: '/learn/$slug'
      path: '/learn/$slug'
      fullPath: '/learn/$slug'
      preLoaderRoute: typeof LearnSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/contact': {
      id: '/api/contact'
      path: '/api/contact'
      fullPath: '/api/contact'
      preLoaderRoute: typeof ApiContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/newsletter/subscribe': {
      id: '/api/newsletter/subscribe'
      path: '/api/newsletter/subscribe'
      fullPath: '/api/newsletter/subscribe'
      preLoaderRoute: typeof ApiNewsletterSubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/internships/apply': {
      id: '/api/internships/apply'
      path: '/api/internships/apply'
      fullPath: '/api/internships/apply'
      preLoaderRoute: typeof ApiInternshipsApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ContactRoute: ContactRoute,
  EventsRoute: EventsRoute,
  Google3fa6f359a7138e5fDothtmlRoute: Google3fa6f359a7138e5fDothtmlRoute,
  InternPortalRoute: InternPortalRoute,
  InternshipsRoute: InternshipsRoute,
  LoginRoute: LoginRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  RoadmapsRoute: RoadmapsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsOfServiceRoute: TermsOfServiceRoute,
  TutorialsRoute: TutorialsRoute,
  VerifyRoute: VerifyRoute,
  ApiContactRoute: ApiContactRoute,
  LearnSlugRoute: LearnSlugRoute,
  RoadmapsSlugRoute: RoadmapsSlugRoute,
  TutorialsSlugRoute: TutorialsSlugRoute,
  VerifyTokenRoute: VerifyTokenRoute,
  ApiInternshipsApplyRoute: ApiInternshipsApplyRoute,
  ApiNewsletterSubscribeRoute: ApiNewsletterSubscribeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
